name = "globlin_fs"
version = "1.0.0"

description = "File system methods for the Gleam file globbing library `globlin`"
licences = ["Apache-2.0"]
repository = { type = "github", user = "apainintheneck", repo = "globlin_fs" }
links = [{ title = "Main Globlin Package", href = "https://hexdocs.pm/globlin/index.html" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
globlin = ">= 2.0.0 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
